#!/bin/bash

commit_regex="^[a-z]{4,12}: [A-Z][[:print:]]{4,60}$"
error_msg="Aborting commit. Your commit message must match with this pattern: /$commit_regex/"

if ! grep -qE "$commit_regex" "$1"; then
	echo "$error_msg" >&2
	exit 1
fi
